# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes_stats', '0003_auto_20171028_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='correction_factor',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='insulin_to_carb_ratio',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
